config/routes.rb
InternetyRobie::Application.routes.draw do

  resources :ads do
    collection do
      get 'my'
    end
  end
  resources :events do
    collection do
      get 'my'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to=>"home#index"
  get "home/index"

  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :owner, :class_name => "User"

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :owner, :class_name => "User"

  attr_accessor :facebook_attenders_ids

  validates_presence_of :name, :start_time, :end_time
  validate :start_and_end_time
  after_create :post_to_facebook
  after_update :update_on_facebook
  before_destroy :destroy_from_facebook

  def on_facebook?
    facebook_id.present?

  end
  def fetch_from_facebook
    owner.social_graph.events.detect{|event| event.identifier == facebook_id} if on_facebook?
  end
  private
  def start_and_end_time
    errors.add(:start_time, "must be before end time") unless self.start_time < self.end_time
  end
  def post_to_facebook
    if owner.social_graph.present?
      event = owner.social_graph.event!(attr_for_facebook)
      event.invite!(:users => facebook_attenders_ids) if facebook_attenders_ids.present?
      update_attribute(:facebook_id, event.identifier)
    end
  end
  def update_on_facebook
    if on_facebook?
      event = fetch_from_facebook
      if event.present?
        invited_ids = event.invited.map(&:identifier)
        event.invite!(:users => facebook_attenders_ids.reject{|attender_id| invited_ids.include?
        (attender_id)}) if facebook_attenders_ids.present?
        event.update(attr_for_facebook)
      end
    end
  end
  def destroy_from_facebook
    if on_facebook?
      event = fetch_from_facebook
      event.destroy if event.present?
    end
  end
  def attr_for_facebook
    {:name => name, :description => description, :start_time => start_time, :end_time =>
        end_time, :location => location}
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
      )
    end
    user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :presence=>true

  devise :omniauthable, :omniauth_providers => [:facebook]


  has_many :adminable_events, :class_name => 'Event', :foreign_key => :owner_id
  has_many :adminable_ads, :class_name => 'Ad', :foreign_key => :owner_id

  def social_graph
    if provider == "facebook" && access_token.present?
      FbGraph::User.me(access_token).fetch
    end
  end



end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :update, :delete, :my]

# GET /ads
# GET /ads.json
  def index
    @ads = Ad.all
  end
  def my
    @ads = current_user.adminable_ads
    render :index
  end
# GET /ads/1
# GET /ads/1.json
  def show
  end
# GET /ads/new
  def new
    @ad = Ad.new
  end
# GET /ads/1/edit
  def edit
  end
# POST /ads
# POST /ads.json
  def create
    @ad = current_user.adminable_ads.new(ad_params)
    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ad }
      else
        format.html { render action: 'new' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end
# PATCH/PUT /ads/1
# PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end
# DELETE /ads/1
# DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end
  private
# Use callbacks to share common setup or constraints between actions.
  def set_ad
    @ad = Ad.find(params[:id])
  end
# Never trust parameters from the scary internet, only allow the white list through.
  def ad_params
    params.require(:ad).permit(:title, :description, :location, :owner_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email,:password) }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :update, :delete, :my]

  def my
    @events = current_user.adminable_events
    render :index
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.adminable_events.new(event_params)
    @event.facebook_attenders_ids = params[:event][:facebook_attenders_ids]

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.adminable_events.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_time, :end_time, :location, :owner_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    puts "sad"
    if @user.persisted?
      @user.update_attribute(:access_token, request.env["omniauth.auth"].credentials.token)
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :locationstring %><br>
    <%= f.text_field :locationstring %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<h1>Listing ads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Locationstring</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.title %></td>
        <td><%= ad.description %></td>
        <td><%= ad.locationstring %></td>
        <td><%= ad.owner.name %></td>
        <td><%= link_to 'Show', ad %></td>
        <td><%= link_to 'Edit', edit_ad_path(ad) %></td>
        <td><%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<h1>New ad</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<p>
  <strong>Locationstring:</strong>
  <%= @ad.locationstring %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @ad.owner.name %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being
            saved:</h2>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :start_time %><br>
      <%= f.datetime_select :start_time %>
    </div>
    <div class="field">
      <%= f.label :end_time %><br>
      <%= f.datetime_select :end_time %>
    </div>
    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>

    <% if current_user.social_graph.present? && (f.object.new_record? || f.object.on_facebook?) %>
        <div>
          <h4>Invite Friends</h4> <ul>
          <% current_user.social_graph.friends.each do |friend| -%> <li>
          <%= check_box_tag 'event[facebook_attenders_ids][]', friend.identifier -%> <%= image_tag "http://graph.facebook.com/#{friend.identifier}/picture" -%> <%= friend.name -%>
        </li>
          <% end -%>
        </ul> </div>
    <% else -%>
       NIE UDAŁO SIĘ current_+user.social.graph.present?

        <%= current_user.inspect %>     <br/>
        <%= current_user.social_graph %>     <br/>
        <%= f.object.new_record? %>     <br/>
        <%= f.object.on_facebook? %>     <br/>

    <% end -%>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) if event.owner == current_user %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } if event.owner == current_user %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<% if user_signed_in? -%>
    <h2>Hello: <%= current_user.name -%></h2>
    <ul>
      <li>
        <%= link_to 'Edit account', edit_user_registration_path %>
      </li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
      <li>
        <%= link_to 'Browse Events', events_path -%>
      </li>
      <li>
        <%= link_to 'Browse Ads', my_ads_path -%>
      </li>
    </ul>
<% else -%>
    <ul>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
      <li>
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
      </li>
      <li>
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>
    </ul>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InternetyRobie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>